<a href="https://colab.research.google.com/github/amulyaashwath/AIML.EXAM-/blob/main/linalg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating matrix using array feature in numpy 

In [2]:
import numpy as np 
a=np.array([[1,3,7,2],[5,8,-9,0],[6,-7,11,12]])
print("a=",a)

a= [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


Matrix addition and subtraction 

In [3]:
import numpy as np
a=np.array([[0,1],[-2,-3]])
b=np.array([[1,0],[3,-2]])
c=a+b
print("a+b=",c)
c=a-b
print("a-b=",c)

a+b= [[ 1  1]
 [ 1 -5]]
a-b= [[-1  1]
 [-5 -1]]


Multiplication matrix method 

In [6]:
c=np.dot(a,b)
print("a*b=",c)
c=np.matmul(a,b)
print("a*b=",c)
c=a.dot(b)
print("a*b=",c)

a*b= [[  3  -2]
 [-11   6]]
a*b= [[  3  -2]
 [-11   6]]
a*b= [[  3  -2]
 [-11   6]]


Matrix transpose 

In [7]:
import numpy as np 
a=np.array([[1,3,7,2],[5,8,-9,0],[6,-7,11,12]])
print("a=");print(a)
Atr=np.transpose(a)
print("transpose of a ");print(Atr)

a=
[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]
transpose of a 
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]


Creating Determinant

In [8]:
import numpy as np
import numpy.linalg as la 
a=np.array([[1,2],[3,4]])
adet=la.det(a)
print(adet)
b=np.array([[-1,3,0],[2,1,-5],[1,4,-2]])
bdet=la.det(b)
print(bdet)

-2.0000000000000004
-21.00000000000001


Inverse of Matrix

In [9]:
import numpy as np
import numpy.linalg as la 
a=np.array([[1,2],[3,4]])
ainv=la.inv(a)
print(ainv)
b=np.array([[-1,3,0],[2,1,-5],[1,4,-2]])
binv=la.inv(b)
print(biv)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


Eigen Values 

In [11]:
import numpy as np
import numpy.linalg as la
a=np.array([[0,1],[-2,-3]])
aeig,v=la.eig(a)
print(aeig)

[-1. -2.]


Solving linear algebra

In [12]:
import numpy as np
import numpy.linalg as la 
a=np.array([[1,2],[3,4]])
b=np.array([[5],[6]])
ainv=la.inv(a)
x=ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]
